### ISSUE TITLE
Spotlight shadows are not working

### ISSUE THREAD

**Issue by N8n5h** [armory3d/iron#105]
![image](https://user-images.githubusercontent.com/42382648/95542238-9eabc380-09cb-11eb-9e48-0dc43e320758.png)

thanks to @QuantumCoderQC and @MoritzBrueckner, the issue was pinpointed to this commit https://github.com/armory3d/iron/commit/e1c49f7b5287ee54f8b6ad87acb0770bb887fc3f

It seems the problem is with those remnants ifs from the refactor https://github.com/armory3d/iron/blob/fc1a6a5e47a495c5dfcec30d8b6f756cc92b71fc/Sources/iron/object/Uniforms.hx#L816

I pushed a simple fix which seems to solve the issue, https://github.com/N8n5h/iron/commit/ac2a0edd6f73174d7fa1ce9559a866d7dab0d048
But not sure if this is the best solution performance-wise since I'm unfamiliar with how Haxe's switch works.
what do you think @luboslenco ?

Maybe something like 
```Haxe
if (c.link.startsWith("_biasLightWorldViewProjectionMatrixSpot")) {
      ...
} else if (c.link.startsWith("_biasLightViewProjectionMatrixSpot")) {
      ...
} else {
   switch(c.link) {
      ...
   }
}
``` 
could be a better solution instead?

**Comment by luboslenco** [comment]
Nice! Should be resolved now.
