### ISSUE TITLE
Set limit framerate

### ISSUE THREAD

**Issue by e1e5en-gd** [armory3d/iron#107]
I would like to be able to change the number of frames per second, because for web applications and for smartphones 60 frames is a lot (`Vsync`- 60 or no limit, it is known).
I studied the source code of the `Armory` engine and its abstraction levels (`Armory`, `Iron`, `Kha`) and came to the following conclusions:
1. there is currently no way to change the number of frames via `Armory`and `Iron`;
2. there are also no settings via `Kha`:
- the `render` function that is registered to execute as `kha.System.notifyOnFrames()` and will run with a limit of 60. Because it depends on the call event on the chosen platform;
- adds the `update` function to the `Scheduler` and you can specify the frequency of more execution. You can specify a value of 30 and it turns out that the scene is render 2 times, and updated 1 time. Because neither are executed in parallel.
To specify this setting, either in the `Display` class (it is located in `ArmorySDK\Kha\Backends\[target_name]\kha`), you need to specify a value for the platform in the `get_frequency()` function. Or, in the `Time` class of the `Iron` engine (`ArmorySDK\iron\Sources\iron\system`) in the `init()` function, specify the frequency value instead of what is there.

Can make changes to `Iron`:
To make the `render` function run with the same frequency as `update`, you can register an “empty function” in `kha.System.notifyOnFrames()` (only to store the value from the `frames[0]` array passed in the `framebuffer` field). And execute the real function in `update`. In this case, the empty function will still be executed 60 times, but the “workers” will only be 30.
And for the “correct” display of the FPS value in the `DebugConsole` and in the `Get FPS` node, it is necessary to correct that the time during the calculation was used from `Scheduler`, and not the real one (which will produce 60 FPS).
I haven’t been able to find any other way to limit the frames per second other than upgrading the `Iron`. In this case, you can display settings in the nodes or the _Blender_ interface. But this is a limitation at the level of one of the abstraction layers. And make it optional, if the user left the FPS limit at 60, then everything will work according to the current algorithm.

The developers `Kha` are in no hurry to introduce such a possibility (judging by the topics on the forum (http://forum.kode.tech/topic/329/building-a-desktop-app-render-on-demand) and the request in git (https://github.com/Kode/Kha/issues/320)).

I wrote the results of my searches here (https://forums.armory3d.org/t/set-limit-framerate-ln-for-get-fps/4286/8).

What do you think about this? Is there any other way to solve this problem?

**Comment by luboslenco** [comment]
Sorry but it would be the best to implement this feature in Kha, especially since Robert is in favor of it at https://github.com/Kode/Kha/issues/320. He might not get into implementing it yet but it usually also means he would accept the pull request. Kha already has a way to set frequency via https://github.com/Kode/Kha/blob/master/Sources/kha/FramebufferOptions.hx#L5, so I guess it is 'only' missing the implementation in the [html5 backend](https://github.com/Kode/Kha/tree/master/Backends/HTML5/kha).

**Comment by e1e5en-gd** [comment]
1. FramebufferOptions - I can't figure out how to get the current instance in the code to set its settings. If you tell me, I will be very grateful.
If there is such a possibility, then you can simply configure the execution settings when initializing Iron.

2. And can make it possible to set the frequency for the update function when added to the Scheduler? Iron already does this. https://github.com/armory3d/iron/blob/ae712058749275ba8a033fd7cff6f9940f83fcaa/Sources/iron/App.hx#L47
https://github.com/armory3d/iron/blob/ae712058749275ba8a033fd7cff6f9940f83fcaa/Sources/iron/system/Time.hx#L20
The logic of working with Kha will not change here, but only the setting.

**Comment by moisesjpelaez** [comment]
I'm not a software developer but I think if the end user wants to actually make a game this user shouldn't be modifying lower level libraries like Kha and the engine should adapt to what Kha currently offers. I think this issue should be reopened and I propose to set the fps cap should be set on here:
![image](https://github.com/armory3d/iron/assets/24682046/a7e39a44-9b1f-40af-afda-0ddd18343cba)

While I'll be investigating and giving it a try on my own I'll appreciate if someone can point me out which source files I can read to speed up and see what I can do.
