### ISSUE TITLE
iron/data/Geometry.hx --->  Null<kha.graphics4.VertexBuffer> has no field lockInt16

### ISSUE THREAD

**Issue by Lykdraft** [armory3d/iron#119]
Not sure if this is a better fit for Kha or Iron, but looks like the latter to me.
VS Code will spit this error when the Haxe Language Server wants to start.

```
Haxe language server started
Haxe Path: /armsdk/Kha/Tools/haxe/haxe-osx
Using --server-connect
Haxe connected!
Listening on port 6000
Failed - try fixing the error(s) and restarting the language server:

/armsdk/iron/Sources/iron/data/Geometry.hx:222: characters 18-27 : Null<kha.graphics4.VertexBuffer> has no field lockInt16
/armsdk/iron/Sources/iron/data/Geometry.hx:247: characters 27-36 : kha.graphics4.VertexBuffer has no field lockInt16
```

If this rather should be placed in Kha-issues, please let me know.

Best,
tL.

_I also tried to change `lockInt16()` to `lock()` in Geometry.hx
but then (rather obviously) this happens:
` kha.arrays.Float32Array should be kha.arrays.Int16Array`_

**Comment by luboslenco** [comment]
Hi, thanks for report.

It looks like `lockInt16()` is no longer available in the kha/html5 backend:
https://github.com/Kode/Kha/blob/master/Backends/HTML5/kha/graphics4/VertexBuffer.hx

But it's still available in the other kha backends:
https://github.com/Kode/Kha/blob/master/Backends/Kinc-hxcpp/kha/graphics4/VertexBuffer.hx
https://github.com/Kode/Kha/blob/master/Backends/Krom/kha/graphics4/VertexBuffer.hx

Here are related Kha commits I found:
https://github.com/Kode/Kha/commit/5c0bf12af2741259f56f321f9f2ba839bc960538
https://github.com/Kode/Kha/commit/2e456d4dc7dcc750d63df110f126434f345f9083

So the `lockInt16()` is being unified with `lock()`, but looks like it's not yet finished in the latest Kha.

(As a temporary workaround [armsdk/Kha](https://github.com/armory3d/Kha) will work in the meantime.)

**Comment by Lykdraft** [comment]
Ah I see, thanks for the info!
