### ISSUE TITLE
Adding as Kha dependency

### ISSUE THREAD

**Issue by nictaylr** [armory3d/iron#17]
Hi,

How can I add `iron` as a dependency to a Kha project? I'm using Kode Studio, but there's unfortunately very little documentation ☹️

**Comment by luboslenco** [comment]
Hello,

Adding as a library (eg clone into `kha_project/Libraries` folder + `addLibrary("iron");` in khafile.js) should work.

However the docs are none - what would you like to achieve? I can start writing some if there is interest. Right now this lib is only used in Armory (but does not depend on it), the docs will be needed anyway.

**Comment by nictaylr** [comment]
I would really, really love to see some documentation.

I want to use this engine in a standalone Kha project without Armory in Blender.

**Comment by luboslenco** [comment]
There is some barebones setup doc available now, will expand more as the time goes. Feel free to open more issues on specific topics.

http://armory3d.org/iron/
