### ISSUE TITLE
Broken `iron_format` link in wiki 

### ISSUE THREAD

**Issue by zikorano** [armory3d/iron#175]
The link to iron_format in the wiki is broken. 
> - [iron_format](https://github.com/armory3d/iron_format) for 3D model import

That said, does iron_format still exist? I couldn't find it under armory's repositories

**Comment by luboslenco** [comment]
Fixed the links, thanks for letting me know. It's still possible to pick up the format parsers from https://github.com/armory3d/armorbase/tree/main/Sources/arm/format.

If models can be processed at compile-time then the blender exporter like tong mentions is the better option.
