### ISSUE TITLE
buildVertices function not defined

### ISSUE THREAD

**Issue by fractalfederation** [armory3d/iron#18]
`Compiling shader 8 of 8 (painter-video.vert.glsl).
C:\Users\blake\Downloads\Armory3D\Armory\armsdk\iron\Sources/iron/data/Geometry.hx:165: characters 2-15 : Unknown identifier : buildVertices

Haxe compiler error.
Build failed, check console
`

The if state is preventing the function from being defined, which is referenced by the copyVertices function.

#if (!arm_deinterleaved)

I moved the copyVertices function within the above if statement but copyVertices is being referenced in another file. I just removed the if statement for now.

**Comment by luboslenco** [comment]
Removed the guards in https://github.com/armory3d/iron/commit/b5c9f571ea65a05aa997f4e549594725aa5dba60, thanks! The function is now also referenced in mesh batching code, which caused this. (This should have only happen with Deinterleaved Buffers enabled in Armory)
