### ISSUE TITLE
Possible Typo: Virutal should be Virtual, I believe... 

### ISSUE THREAD

**Issue by ArgosOz** [armory3d/iron#27]
![screenshot](https://user-images.githubusercontent.com/3820883/33804849-a0a1c9a0-ddbe-11e7-888f-40095be32bf8.png)

**Comment by luboslenco** [comment]
Oh yes, thanks! Fixed in https://github.com/armory3d/iron/commit/031dc68a47a02e8bcaa68c39cbc14a11708a250e.
