### ISSUE TITLE
Any examples of using Iron + haxebullet outside of armory GUI?

### ISSUE THREAD

**Issue by Jarrio** [armory3d/iron#40]
I would like to use just use blender for modeling and do all the coding manually, are there any basic examples of loading and moving a cube which shows the basic project structure?

**Comment by luboslenco** [comment]
Cube / triangle examples:
https://github.com/armory3d/iron_examples

Kha + haxebullet starter:
https://github.com/Kha-Samples/BulletTest

Hopefully more to come soon.

**Comment by Jarrio** [comment]
I saw those guys but I did have issues creating an appropriate export file as well. I followed the setup on the iron page and installed the arm exporter in blender but the exported file (accessed via pressing `space` then `export scene`) to create the `.arm` file and the file just wasn't displaying anything in kha.

**Comment by luboslenco** [comment]
Aha, fixed the .arm exporter, should [work now](https://github.com/armory3d/iron_examples/tree/master/mesh).
