### ISSUE TITLE
[Animation] ObjectAnimation does not work with inconsistent frames count

### ISSUE THREAD

**Issue by FuriouZz** [armory3d/iron#53]
Hello there,

I made some test with object animation and I notice location, scale or rotation can have a `NaN` when my animation got repeated values.

For example, if I read myAction.json, I got that for the scale:

```json
                    {
                        "curve": "bezier",
                        "frames": [
                            1,
                            60
                        ],
                        "frames_control_minus": [
                            -22.034278869628906,
                            36.965721130371094
                        ],
                        "frames_control_plus": [
                            24.034278869628906,
                            83.0342788696289
                        ],
                        "target": "zscl",
                        "values": [
                            1.0,
                            1.0
                        ],
                        "values_control_minus": [
                            1.0,
                            1.0
                        ],
                        "values_control_plus": [
                            1.0,
                            1.0
                        ]
                    }
```

So here (https://github.com/armory3d/iron/blob/master/Sources/iron/object/ObjectAnimation.hx#L133), when you get `frameIndex = 2`, it returns frame 60 and then for `frameIndex = 3` it returns `undefined`.

I fixed the problem for my project. I did not have enough of time to make a pull request. You can found the gist and the gist diff [here](https://gist.github.com/FuriouZz/5f254e7d433beac368f4fa265e95e0eb/revisions) 

Fix: https://gist.github.com/FuriouZz/5f254e7d433beac368f4fa265e95e0eb
Blend+Video: [object_animation.zip](https://github.com/armory3d/iron/files/2660148/object_animation.zip)

PS: My solution seems to break the interpolation because the `if (ti == tii) continue;` =(

**Comment by FuriouZz** [comment]
The problem is when targets do not have the same number of frames.

**Comment by luboslenco** [comment]
Appears to work now.
