### ISSUE TITLE
texture example?

### ISSUE THREAD

**Issue by nanjizal** [armory3d/iron#57]
I am quite close to getting Texture test working with Iron but somewhere I am missing a detail, would it be possible to add example ( without .arm or .blend ) that uses texture or perhaps just some advise in regard to my code.

At moment the white shape is where a texture should show up.
https://nanjizal.github.io/Xperimental/trilateralIron/bin/index.html

The texture and mesh are all setup in:
https://github.com/nanjizal/Xperimental/blob/master/trilateralIron/Sources/iron/helper/TextureColorMesh.hx

It works in a similar way to my SingleColorMesh and MultiColorMesh which are also setup in the example, camera works but is currently implemented without lookAt which would also useful to get advise on.

TextureColorMesh is created here:
https://github.com/nanjizal/Xperimental/blob/master/trilateralIron/Sources/Main.hx#L82

Shaders involved
https://github.com/nanjizal/Xperimental/blob/master/trilateralIron/Shaders/painter-image-iron.vert.glsl
https://github.com/nanjizal/Xperimental/blob/master/trilateralIron/Shaders/painter-image-iron.frag.glsl

should only require Trilateral to work so not many dependancies ( TrilateralXtra should not be needed unless I left some imports in ).

I think the uv data is probably fine as I have done similar in Kha see cat in TrilateralBazaar or jigsaw in Xperimental.

**Comment by zicklag** [comment]
I haven't looked into your problem, but here is somebody else who did some experimenting with pure Iron and has an example that might be useful: http://forums.armory3d.org/t/physically-based-rendering-pbr-in-iron/2456.

**Comment by nanjizal** [comment]
zicklag not really he is using a model I am trying to create the model from 2D data so I think it's likely a bit different?  The packing data is not really documented.  I have managed to extrude 2D shapes but not updated iron as yet to understand the shader setup for packing approach on latest although i have some thoughts but not had time to try what I think.  No progress on textures but extrusion now working perhaps could be nice to implement an node for this thinking to look at ttf processing next perhaps.
https://github.com/nanjizal/Xperimental/tree/master/trilateralIroning

**Comment by luboslenco** [comment]
I have added a texture example at:
https://github.com/armory3d/iron_examples/tree/master/texture

It is however loading mesh data from an .arm file. As for building mesh data by hand, does this help?
https://github.com/armory3d/iron_examples/blob/master/triangle/Sources/Main.hx#L53

Some further info on using 16bit vertex data:
https://www.khronos.org/opengl/wiki/Vertex_Specification_Best_Practices#Attribute_sizes

> ... A time-tested alternative is to use normalized GLshorts. To do this, you rearrange your model space data so that all positions are packed in a [-1, 1] box around the origin.  ...
