### ISSUE TITLE
uv's and short4norm - uv4 and tex4 ?

### ISSUE THREAD

**Issue by nanjizal** [armory3d/iron#61]
It's important that UV's allow short4norm to mirror triangle coordinates for texture masks.
https://github.com/nanjizal/TrilateralXtra/blob/master/src/trilateralXtra/kDrawing/PolyPainter.hx#L352
For instance used in dynamically generated jigsaw, requires multiple changes perhaps introduction of tex4 and uv4 to the code base for this feature to minimize impact on other uses?

**Comment by luboslenco** [comment]
Should be possible to define custom layout now thanks to super cool PR at https://github.com/armory3d/iron/pull/82.
