### ISSUE TITLE
Allow "sub-meshes" that have their own transform?

### ISSUE THREAD

**Issue by N8n5h** [armory3d/iron#87]
Hi, I'm trying to have multiple separated circles that co-exist in the same geometry to billboard to the camera to produce caps for this https://github.com/armory3d/armory/issues/810 and emulate the behavior of caps in Blender. 

Now the problem is that I can't use the [current billboard implementation](https://github.com/armory3d/iron/blob/79ddd0f49c046890203aa45afd2c9d1fb027bf00/Sources/iron/object/Uniforms.hx#L701) because it uses the object.transform, so the transformation of each "individual separated parts" that could exist inside a geometry are completely ignored and assumed to be one big mesh. 

The easiest solution probably would be to simply separate the circles in multiple objects, but I prefer the more complicated one to save performance and space :smile:.

While I was digging the code, I noticed that this non-feature [affects mesh culling too](https://github.com/armory3d/iron/blob/79ddd0f49c046890203aa45afd2c9d1fb027bf00/Sources/iron/object/MeshObject.hx#L164) and either the whole mesh is culled or not, which leads to what is shown in the picture: an individual sub-mesh (blue sphere) not being culled when it should. So I think this could help mesh culling too.
![image](https://user-images.githubusercontent.com/42382648/79807861-86bf8500-8342-11ea-81da-0ce5c549b160.png)

So I assume having an array of transforms or simply an array of "pivot point" for each individual "sub-mesh" and feed that to the object uniform and the mesh culling could help it.

The problem is, which I was mostly stuck with, how a "sub-mesh" could be defined? Index arrays maybe? That could work if they have different materials, but the "problem" with that is that the exporter groups meshes that share a material for performance reasons. So maybe one way could be to tell the exporter "hey, I want them separated!"?

What do you think @luboslenco? Or do you have any other idea to solve this?.

**Comment by luboslenco** [comment]
It sounds like using multiple objects fixes all of the issues without adding more complexity. With multiple objects there is per-object transform and culling. If the material is the same for those objects then the pipeline state is not switched - so the performance should be the same as mesh split into sub-meshes - only vertex data will be switched and uniforms applied. 🙂

**Comment by N8n5h** [comment]
And memory-wise it's the same?

Also I think having too much objects per frame may be problematic for [my implementation of the grease pencil animations in Iron](https://github.com/N8n5h/iron/blob/dda8fcb147c6cc12d8545d94ee5ddb8538eb0787/Sources/iron/object/ObjectAnimation.hx#L183), since it basically iterates over all objects references in a frame and makes them visible (or spawn them if it's the first time), and does the same for the previous frame to hide them.
 
Maybe I could change the animation so it's not a problem, but do you have any idea how it should work then to avoid having this issue? I couldn't come up with another other way of implementing it that doesn't add more complexity to the object system...

**Comment by luboslenco** [comment]
Sorry I missed this. Transform will take the biggest part of memory for basic object, it's 3 matrices + 4 vectors. If any excessive memory gets consumed then the object class itself should get more refined / optimized to better handle such cases. Same for switching visibility for many objects - if any slowdown occurs it should be resolved directly in the object / scene system. (I can look into that.)

**Comment by N8n5h** [comment]
Ok, yeah I forgot about this :sweat_smile: 

> so the performance should be the same as mesh split into sub-meshes - only vertex data will be switched and uniforms applied

I must admit that I didn't do more than simple tests, but still I could see that there is definitely a difference in performance between having every piece of circle separated in their own unique object, versus trying to group as much circles as possible in the same draw call.

Fortunately I think I've found a solution that lets me get around adding this extra complexity in Iron, by using the second solution of [this tutorial](www.opengl-tutorial.org/intermediate-tutorials/billboards-particles/billboards/) and then try to either pass the centroid as a bind_param or pass it as a vertex_attribute, which I'm currently trying to do the latter. 

Also, even though it may add extra complexity, I think individual mesh culling is something that should be investigated because having most things in the same object is a very common workflow (characters and buildings comes to mind) in Blender, so it's either that or maybe tailor the exporter to fit better Iron mesh culling in that regard if there is no actual performance loss by doing that I think.
