### ISSUE TITLE
Object's trait is not stopping after the object is removed

### ISSUE THREAD

**Issue by BlackGoku36** [armory3d/iron#88]
@9987 in discord said:
```
When I destroy an object in Armory, the same object can execute other actions.
For example, if I do a
On contact with player --> Destroy self --> Spawn explosion
The explosion spawns!
While in another engines, the explosion cannot get spawned because a destroyed object can't execute code
But if I do this:
Event spawn explosion --> Spawn explosion
On contact with player --> Destroy self --> Execute event "spawn explosion"
Then the explosion doesn't get spawned.
Is there a delay or something after an object gets destroyed? Or will the object execute every node that is connected after the Destroy self?
```
This could have been because at: https://github.com/armory3d/iron/blob/master/Sources/iron/object/Object.hx#L70, the trait is only getting removed from the array but not the main update loop. at that line maybe removeTrait() https://github.com/armory3d/iron/blob/master/Sources/iron/object/Object.hx#L137 could be used.

**Comment by luboslenco** [comment]
Hm that already happens,
https://github.com/armory3d/iron/blob/master/Sources/iron/object/Object.hx#L70
calls `trait.remove()`
https://github.com/armory3d/iron/blob/master/Sources/iron/Trait.hx#L23
which then calls `object.removeTrait()`.
If possible please reopen with example at armory.
